server:
  port: 4040
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Order_Details?createDatabaseIfNotExist=true
    username: root
    password: shan1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
<<<<<<< HEAD
      ddl-auto: update
=======
      ddl-auto: create
>>>>>>> c18dfea47abcea75a4194587390abdad8369f5b0
