server:
  port: 4040
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdetailsDB?createDatabaseIfNotExist=true
    username: root
    password: shan1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop