server:
  port: 2120

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Account_Service?createDatabaseIfNotExist=true
    username: root
    password: shan1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
authserver:
  clientid: mobile
  clientsecret: pass
